### ISSUE TITLE
Tools are not Loading

### ISSUE THREAD

**Issue by donjuanmon** [ironmansoftware/poshtools-issues#17] opened 2020-03-03 15:24 UTC
Hello,

We have been communicating over Email but thought it would be more appropriate here. The VSCode module does not appear to be working. It never prompted to register the software (Succeeded through Powershell Pad product) and known installed modules are not appearing. This is the output from logging enabled:

```
PS C:\Users\USER\windows-scripts> Import-Module 'c:\Users\USER\.vscode\extensions\ironmansoftware.powershellprotools-5.8.3\out\PowerShellProTools.VSCode.psd1' -ArgumentList @($true)
Starting server with PSScriptRoot: C:\Users\USER\.vscode\extensions\ironmansoftware.powershellprotools-5.8.3\out 
PS C:\Users\USER\windows-scripts> Importing PowerShell Pro Tools module.
Importing PowerShell Pro Tools for VS Code module.
Starting server with PSScriptRoot: C:\Users\USER\.vscode\extensions\ironmansoftware.powershellprotools-5.8.3\out 
PoshProTools runspace already exists. Not starting server.
Starting named pipe server.
Received command:
Exception in server: System.IO.IOException: Pipe is broken.
   at System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServer()
   at System.IO.Pipes.NamedPipeServerStream.CheckConnectOperationsServerWithHandle()
   at System.IO.Pipes.NamedPipeServerStream.WaitForConnection()
   at PowerShellToolsPro.Cmdlets.VSCodeHelpers.StartServer(String psScriptRoot) in D:\a\1\s\PowerShellToolsPro.Cmdlets\VSCodeHelpers.cs:line 103
Received command: Get-PoshProToolsLicense | ForEach-Object { [PSCustomObject]@{ UserName = $_.UserName; EndDate = $_.EndDate.ToString(); IsTrial = $_.IsTrial; Status = $_.Status.ToString() } } | ConvertTo-Json
Output is not null. Writing output (119 bytes).
Received command: Get-PoshProToolsLicense | ForEach-Object { [PSCustomObject]@{ UserName = $_.UserName; EndDate = $_.EndDate.ToString(); IsTrial = $_.IsTrial; Status = $_.Status.ToString() } } | ConvertTo-Json
Output is not null. Writing output (119 bytes).
Received command: Get-PoshProToolsLicense | ForEach-Object { [PSCustomObject]@{ UserName = $_.UserName; EndDate = $_.EndDate.ToString(); IsTrial = $_.IsTrial; Status = $_.Status.ToString() } } | ConvertTo-Json
Output is not null. Writing output (119 bytes).
Received command: Get-Module -ListAvailable | Group-Object -Property Name | Sort-Object Name | ConvertTo-Json -Depth 3 
Output is not null. Writing output (215912 bytes).
Received command: Get-PoshProToolsLicense | ForEach-Object { [PSCustomObject]@{ UserName = $_.UserName; EndDate = $_.EndDate.ToString(); IsTrial = $_.IsTrial; Status = $_.Status.ToString() } } | ConvertTo-Json
Output is not null. Writing output (119 bytes).
Received command: Get-PSProvider | Select-Object -ExpandProperty Name | ConvertTo-Json
Output is not null. Writing output (125 bytes).
Received command: Get-PoshProToolsLicense | ForEach-Object { [PSCustomObject]@{ UserName = $_.UserName; EndDate = $_.EndDate.ToString(); IsTrial = $_.IsTrial; Status = $_.Status.ToString() } } | ConvertTo-Json
Output is not null. Writing output (119 bytes).
Received command: Get-PoshProToolsLicense | ForEach-Object { [PSCustomObject]@{ UserName = $_.UserName; EndDate = $_.EndDate.ToString(); IsTrial = $_.IsTrial; Status = $_.Status.ToString() } } | ConvertTo-Json
Output is not null. Writing output (119 bytes).
Received command: GetVariables
Output is not null. Writing output (6246 bytes).

```

In this case, I was clicking through the various tools.

**Comment by adamdriscoll** [comment] 2020-03-03 17:39
@stjani-kjani 

I took a look into this issue and I'm seeing 2 things happen. 

1. I'm seeing this error just as you were. It looks like when opening the PowerShell Pro Tools activity pane before the PowerShell extension is loaded will result in this error. I have a resolution for this and will be in version 5.8.4. You may still see an error in the start up logging but it's benign. 

![error](https://user-images.githubusercontent.com/1256531/75802745-76bff780-5d3a-11ea-837b-f70f20cff663.png)

2. When loading the module view in the activity pane 2 things are happening. First, it's calling Get-Module -ListAvailable to find all the modules listed on your machine. Then, any modules that were installed from the Gallery, it's using Find-Module to check the Gallery to see if there are updates. The problem is the second step takes a long time because the Gallery can be slow to respond. This ends up with a ton of PowerShell commands waiting on the same runspace and it ends up preventing the extension from processing any more commands. The module then gets into a invalid state and no longer seems to behave correctly at all. 

I've drastically improved the performance of step 2 by offloading the Find-Module command to a different process. 

I was able to reproduce the issue where the form designer would not open after getting in this state. 

I was not able to reproduce the issue where known modules were not appearing but I have a feeling it had something to do with the issues I mentioned approve. I'm going to close this issue and release version 5.8.4 later today after doing some additional testing. If you could make sure you are up to date and try to reproduce your issues, that would be very helpful.

**Closed as completed by adamdriscoll** 2020-03-03 17:39 UTC
Labels: bug, visual-studio-code
